//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationInfo
    {
        public int ID { get; set; }
        public string GUID { get; set; }
        public string Number { get; set; }
        public string AppUGUID { get; set; }
        public string AppLogin { get; set; }
        public string AppName { get; set; }
        public string DriverUGUID { get; set; }
        public string DriverLogin { get; set; }
        public string DriverName { get; set; }
        public string LeadUGUID { get; set; }
        public string LeadLogin { get; set; }
        public string LeadName { get; set; }
        public string CGUID { get; set; }
        public string LicencePlate { get; set; }
        public string Reason { get; set; }
        public string Department { get; set; }
        public string Origin { get; set; }
        public int Distance { get; set; }
        public string Destination { get; set; }
        public System.DateTime GoDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public System.DateTime ApplicationDate { get; set; }
        public int Status { get; set; }
    }
}
