//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarsInfo
    {
        public int ID { get; set; }
        public string GUID { get; set; }
        public string Number { get; set; }
        public string LicencePlate { get; set; }
        public int Seating { get; set; }
        public string CarModel { get; set; }
        public string CarColor { get; set; }
        public string CarBrand { get; set; }
        public double OilWear { get; set; }
        public int OilType { get; set; }
        public int Mileage { get; set; }
        public int Status { get; set; }
    }
}
