//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsInfo
    {
        public int ID { get; set; }
        public string GUID { get; set; }
        public string UGUID { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public string Name { get; set; }
        public System.DateTime EditDate { get; set; }
        public int Type { get; set; }
        public int Status { get; set; }
    }
}
