//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public int ID { get; set; }
        public string GUID { get; set; }
        public string Login { get; set; }
        public string Pwd { get; set; }
        public string Name { get; set; }
        public int Gender { get; set; }
        public string Phone { get; set; }
        public int Type { get; set; }
        public System.DateTime LoginDate { get; set; }
        public System.DateTime AddDate { get; set; }
        public Nullable<System.DateTime> OfficeDate { get; set; }
        public string Department { get; set; }
        public int Status { get; set; }
        public Nullable<int> Mileage { get; set; }
        public Nullable<int> Total { get; set; }
    }
}
